Server:
  address:
  port: 8900   # 服务器监听的端口号
  Servlet:
    contextpath: /system-user

# 数据库配置项
DataBase:
  url: 101.201.174.45  # 数据库连接地址
  port: 3306  # 数据库服务端口
  userName: root  # 连接数据库的用户名
  password: 123456  # 用户名对应的密码
  name: Las  # 数据库名称
  urladditionalparameters:  # 额外的数据库连接参数
